version: "3"
services:
    node:
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/server
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 33063:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: root
volumes:
    db-data: {}